require("legendary").setup({
	keymaps = {
		-- {
		-- 	"<leader>gh",
		-- 	"<cmd>Lspsaga lsp_finder<cr>",
		-- 	description = "Find Definition",
		-- 	opts = { silent = true },
		-- },
		-- {
		-- 	"<leader>gs",
		-- 	"<cmd>Lspsaga show_line_diagnostics<cr>",
		-- 	description = "Show Line Diagnostics",
		-- 	opts = {
		-- 		silent = true,
		-- 	},
		-- },
		-- {
		-- 	"<leader>sc",
		-- 	"<cmd>Lspsaga show_cursor_diagnostics<cr>",
		-- 	description = "Show Cursor Diagnostics",
		-- 	opts = {
		-- 		silent = true,
		-- 	},
		-- },
		-- {
		-- 	"<leader>ci",
		-- 	"<cmd>Lspsaga incoming_calls<cr>",
		-- 	description = "Incoming Calls",
		-- 	opts = { silent = true },
		-- },
		-- {
		-- 	"<leader>co",
		-- 	"<cmd>Lspsaga outgoing_calls<cr>",
		-- 	description = "Outgoing Calls",
		-- 	opts = { silent = true },
		-- },
		-- {
		-- 	"<leader>gp",
		-- 	"<cmd>Lspsaga peek_definition<cr>",
		-- 	description = "Peek Definition",
		-- 	opts = { silent = true },
		-- },
		-- {
		-- 	"<leader>gd",
		-- 	"<cmd>Lspsaga goto_definition<cr>",
		-- 	description = "Go to Definition",
		-- 	opts = { silent = true },
		-- },
		-- {
		-- 	"<leader>gt",
		-- 	"<cmd>Lspsaga peek_type_definition<cr>",
		-- 	description = "Peek Type Definition",
		-- 	opts = { silent = true },
		-- },
		-- {
		-- 	"K",
		-- 	"<cmd>Lspsaga hover<cr>",
		-- 	description = "Hover",
		-- 	opts = { silent = true },
		-- },
		-- {
		-- 	"<leader>gr",
		-- 	"<cmd>Lspsaga rename<cr>",
		-- 	description = "Rename",
		-- 	opts = { silent = true },
		-- },
		-- {
		-- 	"<leader>pf",
		-- 	"<cmd>Telescope find_files<cr>",
		-- 	description = "Telescope Find Files",
		-- 	opts = { silent = true },
		-- },
		-- {
		-- 	"<leader>t",
		-- 	"<cmd>TroubleToggle<cr>",
		-- 	description = "Toggle Trouble",
		-- 	opts = { silent = true },
		-- },
		-- {
		-- 	"<leader>u",
		-- 	"<cmd>UndotreeToggle<cr>",
		-- 	description = "Toggle Undotree",
		-- 	opts = { silent = true },
		-- },
		-- {
		-- 	"<leader>lg",
		-- 	"<cmd>Legendary<cr>",
		-- 	description = "Open Legendary Finder UI",
		-- 	opts = { silent = true },
		-- },
		-- {
		-- 	"<leader>lg",
		-- 	"<cmd>Legendary<cr>",
		-- 	description = "Open Legendary Finder UI",
		-- 	opts = { silent = true },
		-- },
	},
	commands = {
		-- Git
		{ ":Git", description = "Open git fugitive window" },
		{ ":Git add .", description = "Add current index" },
		{ ":Git commit", description = "Commit current index" },
		{ ":Git push [remote] [branch]", description = "Push current commit head", unfinished = true },
		{ ":Git pull [remote] [branch]", description = "Pull from remote branch", unfinished = true },
		{ ":Git fetch", description = "Fetch from remote branch" },
		{ ":Git merge", description = "Merge current branch" },
		{ ":Git checkout", description = "Checkout current branch" },
		{ ":Git checkout -b [branch]", description = "Create new branch", unfinished = true },
		{ ":Git branch", description = "List branches" },
		{ ":Git log", description = "Git log" },
		{ ":Git log --oneline", description = "Git log oneline" },
		{ ":Git log --graph", description = "Git log graph" },
		{ ":Git status", description = "Git status" },
		{ ":Git diff", description = "Git diff" },
		{ ":Git rm", description = "Git rm" },
		{ ":Git rm --cached", description = "Git rm --cached" },
		{ ":Git reset", description = "Git reset" },
		{ ":Git blame", description = "Git blame" },
		{ ":Git show", description = "Git show" },
		{ ":Git grep", description = "Git grep" },
		{ ":Git grep -n", description = "Git grep for current word" },

		-- LSP
		{ ":LspStop", description = "Stop lsp server" },
		{ ":LspRestart", description = "Restart lsp server" },
		{ ":LspStart", description = "Start lsp server" },
		{ ":LspStopAll", description = "Stop all lsp server" },
		{ ":LspStartAll", description = "Start all lsp server" },
		{ ":LspInfo", description = "Lsp info" },
		{ ":LspInstall", description = "Lsp install" },
		{ ":LspUninstall", description = "Lsp uninstall" },
		{ ":LspUpdate", description = "Lsp update" },
		{ ":LspStatus", description = "Lsp status" },
		{ ":LspLog", description = "Lsp log" },

		-- DAP
		{ ":DapContinue", description = "Continue" },
		{ ":DapToggleBreakpoint", description = "Toggle breakpoint" },
		{ ":DapNext", description = "Next" },
		{ ":DapStepOver", description = "Step over" },
		{ ":DapStepInto", description = "Step into" },
		{ ":DapStepOut", description = "Step out" },
		{ ":DapTerminate", description = "Terminate" },
		{ ":DapToggleRepl", description = "Toggle repl" },
		{ ":DapToggleConsole", description = "Toggle console" },
		{ ":DapAttach", description = "Attach" },

		-- Mason
		{ ":Mason", description = "Mason" },
		{ ":MasonInstall [module]", description = "Mason install", unfinished = true },
		{ ":MasonUninstall [module]", description = "Mason uninstall", unifinished = true },
		{ ":MasonUpdate", description = "Mason update" },
		{ ":MasonStatus", description = "Mason status" },

		-- NvimTree
		{ ":NvimTreeToggle", description = "Toggle nvim tree" },
		{ ":NvimTreeRefresh", description = "Refresh nvim tree" },
		{ ":NvimTreeFocus", description = "Focus nvim tree" },
		{ ":NvimTreeOpen", description = "Open nvim tree" },
		{ ":NvimTreeClose", description = "Close nvim tree" },
		{ ":NvimTreeResize", description = "Resize nvim tree" },
		{ ":NvimTreeCollapse", description = "Collapse nvim tree" },

		-- Telescope
		{ ":Telescope", description = "Telescope" },
		{ ":Telescope live_grep", description = "Telescope live_grep" },
		{ ":Telescope find_files", description = "Telescope find_files" },
		{ ":Telescope buffers", description = "Telescope buffers" },
		{ ":Telescope help_tags", description = "Telescope help_tags" },
		{ ":Telescope oldfiles", description = "Telescope oldfiles" },
		{ ":Telescope keymaps", description = "Telescope keymaps" },
		{ ":Telescope diagnostics", description = "Telescope diagnostics" },
		{ ":Telescope colorscheme", description = "Telescope colorscheme" },
		{ ":Telescope grep_string", description = "Telescope grep_string" },
		{ ":Telescope git_files", description = "Telescope git_files" },
		{ ":Telescope git_bcommits", description = "Telescope git_bcommits" },
		{ ":Telescope git_commits", description = "Telescope git_commits" },
		{ ":Telescope git_branches", description = "Telescope git_branches" },
		{ ":Telescope git_stash", description = "Telescope git_stash" },
		{ ":Telescope git_status", description = "Telescope git_status" },

		-- Treesitter
		{ ":TSInstall [module]", description = "Install treesitter module", unfinished = true },
		{ ":TSUpdate", description = "Update treesitter" },
		{ ":TSToggle", description = "Toggle treesitter" },
		{ ":TSEnable", description = "Enable treesitter" },
		{ ":TSDisable", description = "Disable treesitter" },
		{ ":TSSetup", description = "Setup treesitter" },

		-- Packer
		{ ":PackerSync", description = "Sync packer" },
		{ ":PackerUpdate", description = "Update packer" },
		{ ":PackerClean", description = "Clean packer" },
		{ ":PackerCompile", description = "Compile packer" },
		{ ":PackerInstall", description = "Install packer" },
		{ ":PackerStatus", description = "Packer status" },
	},
	select_prompt = "Commands Palette",
	extensions = {
		nvim_tree = true,
	},
})

vim.keymap.set({ "n", "v" }, "<leader>lg", "<cmd>Legendary<cr>", { silent = true })
